config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  as :user do
    get '/nurses/sign_up', :to => 'devise/registrations#new'
    get '/customers/sign_up', :to => 'devise/registrations#new'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  resources :dashboard, only: :index

  get 'terms-and-conditions' => 'terms_and_conditions#index', as: 'terms_and_conditions'
  get 'privacy-policy' => 'privacy_policy#index', as: 'privacy_policy'
  get 'faq' => 'faq#index', as: 'faq'
  get 'contact' => 'contact#index', as: 'contact'

  namespace :dashboard do
    get 'profile' => 'profile#show', as: 'profile'
    get 'profile/edit' => 'profile#edit', as: 'edit_profile'
    put 'profile/update' => 'profile#update', as: 'update_profile'
  end

  resources :services, only: [:new, :create] do
    get 'chose_assistent', to: 'services#chose_assistent', as: 'chose_assistent'
  end

  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
  end

  root 'home#index'
end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id          :integer          not null, primary key
#  customer_id :integer
#  nurse_id    :integer
#  description :text
#  comments    :text
#  price       :float
#  rating      :integer
#  state       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  address_id  :integer
#  specialty   :string
#  start_date  :datetime
#  end_date    :datetime
#
# Indexes
#
#  index_services_on_address_id   (address_id)
#  index_services_on_customer_id  (customer_id)
#  index_services_on_nurse_id     (nurse_id)
#

class Service < ActiveRecord::Base
  belongs_to :customer, foreign_key: 'customer_id', class_name: Customer
  belongs_to :nurse, foreign_key: 'nurse_id', class_name: Nurse
  belongs_to :address

  accepts_nested_attributes_for :address

  state_machine :state, initial: :pending do
    event :accept do
      transition [:pending, :dealing] => :accepted
    end

    event :reject do
      transition pending: :rejected
    end

    event :deal do
      transition pending: :dealing
    end

    event :cancel do
      transition accepted: :canceled
    end

    event :complete do
      transition accepted: :completed
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController

  def new
    @service = Service.new
    @service.build_address
  end

  def create
    @service = Service.new service_params
    @service.address = check_address
    @service.start_date = build_date[0]
    @service.end_date = build_date[1]

    if @service.save
      respond_to do |format|
        format.html { redirect_to service_chose_assistent_path(@service) }
      end
    end
  end

  private

  def service_params
    params.require(:service).permit(
      :start_date,
      :end_date,
      :specialty,:address_attributes => [:line_1, :line_2, :state, :city, :zip_code]
    )
  end

  def check_address
    address = Address.find_by(
      line_1: @service.address.line_1,
      zip_code: @service.address.zip_code
    )

    if address && address.user_id?
      current_user.address
    else
      service_params[:address_attributes]
    end
  end

  def build_date
    date = []
    date[0] = ParseDate.new(service_params.select{ |k, v| k.to_s.index('start_date(') == 0 }.sort.map{ |p| p[1].to_i }).convert
    date[1] = ParseDate.new(service_params.select{ |k, v| k.to_s.index('end_date(') == 0 }.sort.map{ |p| p[1].to_i }).convert
    date
  end

end

app/helpers/service_helper.rb
module ServiceHelper
  def service_date(service)
    I18n.localize service.created_at, format: :history_details
  end

  def service_state_badge(service)
    content_tag :span, class: "badge #{service.state}" do
      service.state
    end
  end

  def display_service_price(service)
    number_to_currency(service.price, precision: 2)
  end

end

app/views/services/_service.html.slim
= link_to '#' do
  .col.s12.m12.l4
    .card.service-card
      .card-content
        span.card-title.activator.grey-text.text-darken-4
          = service.nurse.full_name
        .row.grey-text.text-darken-3
          span.col.s12 = service.address.try(:line_1)
        .row.grey-text.text-darken-3
          span.col.s6 = service_date(service)
          span.col.s6.right-align = display_service_price(service)
        .row
          == service_state_badge(service)

app/views/services/new.html.slim
.container
  .row
    = form_for @service, as: :service, html: { class: 'col s12 m12 l8 offset-l2', method: :post  }, url: services_path do |f|
      h3.center.light-blue-text.text-darken-4.title
        | Completa tu Perfil
      .row

        = f.fields_for :address do |address_fields|
          .input-field.col.s12
            = address_fields.label 'Calle y Numero *', class: "#{render_error_message(@service, 'address')}"
            br/
            = address_fields.text_field :line_1, autofocus: true, class: "#{render_error_message(@service, 'address')}", value: current_user.full_address[:line_1]

          .input-field.col.s12
            = address_fields.label 'Colonia *', class: "#{render_error_message(@service, 'address')}"
            br/
            = address_fields.text_field :line_2, autofocus: true, class: "#{render_error_message(@service, 'address')}", value: current_user.full_address[:line_2]

          .input-field.col.s12
            = address_fields.label 'Estado *', class: "#{render_error_message(@service, 'address')}"
            br/
            = address_fields.text_field :state, autofocus: true, class: "#{render_error_message(@service, 'address')}", value: current_user.full_address[:state]

          .input-field.col.s12
            = address_fields.label 'Ciudad *', class: "#{render_error_message(@service, 'address')}"
            br/
            = address_fields.text_field :city, autofocus: true, class: "#{render_error_message(@service, 'address')}", value: current_user.full_address[:city]

          .input-field.col.s12
            = address_fields.label 'Codigo Postal *', class: "#{render_error_message(@service, 'address')}"
            br/
            = address_fields.text_field :zip_code, autofocus: true, class: "#{render_error_message(@service, 'address')}", value: current_user.full_address[:zip_code]

        .input-field.col.s12
          = f.label 'Fecha de Inicio *', class: "#{render_error_message(@service, 'start_date')}"
          br/
          = f.datetime_select(:start_date, prompt: { day: 'Elegir Dia', month: 'Elegir Mes', year: 'Elegir Año' }, class: "#{render_error_message(@service, 'start_date')}")

        .input-field.col.s12
          = f.label 'Fecha de Termino *', class: "#{render_error_message(@service, 'end_date')}"
          br/
          = f.datetime_select(:end_date, prompt: { day: 'Elegir Dia', month: 'Elegir Mes', year: 'Elegir Año' })

        .input-field.col.s12
          = f.label 'Especialidades *', class: "#{render_error_message(@service, 'specialty')}"
          br/
          = f.select(:specialty, GlobalConstants::SPECIALTIES, prompt: 'Seleccione especialidad')

      .row.actions
        .input-field.col.s12
          = f.submit "Crear", class: 'waves-effect btn light-blue darken-4'