config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  as :user do
    get '/nurses/sign_up', :to => 'devise/registrations#new'
    get '/customers/sign_up', :to => 'devise/registrations#new'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  resources :dashboard, only: :index

  get 'terms-and-conditions' => 'terms_and_conditions#index', as: 'terms_and_conditions'
  get 'privacy-policy' => 'privacy_policy#index', as: 'privacy_policy'
  get 'faq' => 'faq#index', as: 'faq'
  get 'contact' => 'contact#index', as: 'contact'

  namespace :dashboard do
    get 'profile' => 'profile#show', as: 'profile'
    get 'profile/edit' => 'profile#edit', as: 'edit_profile'
    put 'profile/update' => 'profile#update', as: 'update_profile'
  end

  resources :services, only: [:new, :create] do
    get 'chose_assistent', to: 'services#chose_assistent', as: 'chose_assistent'
  end

  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
  end

  root 'home#index'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#  type                   :string
#  first_name             :string
#  last_name              :string
#  state                  :string
#  phone                  :string
#  avatar_file_name       :string
#  avatar_content_type    :string
#  avatar_file_size       :integer
#  avatar_updated_at      :datetime
#  form                   :string
#  bio                    :text
#  start_date             :datetime
#  end_date               :datetime
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ActiveRecord::Base
  extend Modules::UserExtender

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>", mini: "50x50>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

  has_one :address
  accepts_nested_attributes_for :address,
                                allow_destroy: true

  # callbacks
  after_create :set_default_user_type

  define_user_types

  def full_name
    "#{first_name} #{last_name}"
  end

  def full_address
    {
      line_1:   address.line_1,
      line_2:   address.line_2,
      state:    address.state,
      city:     address.city,
      zip_code: address.zip_code
    }
  end

  private

    def set_default_user_type
      self.update_column(:type, 'Customer') unless self.type
    end
end

app/helpers/user_helper.rb
module UserHelper
  def setup_user(user)
    user.build_address if user.address.nil?
    user
  end
end

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Iniciar sesión", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Olvidaste tu contraseña?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "No recibiste instrucciones de confirmacion?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "No recibiste instrucciones para desbloquear?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Iniciar sesion con #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>