config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  as :user do
    get '/nurses/sign_up', :to => 'devise/registrations#new'
    get '/customers/sign_up', :to => 'devise/registrations#new'
  end

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'


  resources :dashboard, only: :index

  get 'terms-and-conditions' => 'terms_and_conditions#index', as: 'terms_and_conditions'
  get 'privacy-policy' => 'privacy_policy#index', as: 'privacy_policy'
  get 'faq' => 'faq#index', as: 'faq'
  get 'contact' => 'contact#index', as: 'contact'

  namespace :dashboard do
    get 'profile' => 'profile#show', as: 'profile'
    get 'profile/edit' => 'profile#edit', as: 'edit_profile'
    put 'profile/update' => 'profile#update', as: 'update_profile'
  end

  resources :services, only: [:new, :create] do
    get 'chose_assistent', to: 'services#chose_assistent', as: 'chose_assistent'
  end

  authenticated :user do
    root to: "dashboard#index", as: :authenticated_root
  end

  root 'home#index'
end

app/views/layouts/application.slim
doctype html
html
  head
    meta content=("text/html; charset=UTF-8") http-equiv="Content-Type" /
    meta content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no" name="viewport" /
    link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"
    title Asissteme
    == stylesheet_link_tag    'application', media: 'all'
    == javascript_include_tag 'application'
    == csrf_meta_tags
    == favicon_link_tag 'favicon/favicon16.ico'
    == favicon_link_tag 'favicon/favicon32.ico'
    == favicon_link_tag 'favicon/favicon152.png'
  body class="#{controller_name}"
    nav.white.main-nav role="navigation"
      = show_alert_imcomplete_profile

      .nav-wrapper.white
        .container
          == link_to root_path, id: 'logo-container', class: 'brand-logo' do
            == image_tag 'home/logo.svg'
          ul.right.hide-on-med-and-down

            - if user_signed_in?
              li
                = link_to 'Mis servicios', dashboard_index_path, class: 'gray-text'

            li
              - if user_signed_in?
                = link_to('Cerrar Sesión', destroy_user_session_path, :method => :delete, class: 'gray-text')
              - else
                = link_to "Iniciar sesión", new_user_session_path, class: 'gray-text'
            - unless user_signed_in?
              li
                = link_to('Trabaja como asistente', nurses_sign_up_path, class: 'btn waves-effect waves-light light-blue darken-4', id: 'download-button')
          ul#nav-mobile.side-nav
            li
              - if user_signed_in?
                = link_to('Cerrar Sesión', destroy_user_session_path, :method => :delete, class: 'light-blue-text text-darken-4')
              - else
                = link_to "Iniciar sesión", new_user_session_path, class: 'light-blue-text text-darken-4'
            .divider

            - unless user_signed_in?
              li
                = link_to('Trabaja como asistente', nurses_sign_up_path, class: 'light-blue-text text-darken-4')

          a.light-blue-text.text-darken-4.button-collapse data-activates="nav-mobile" href="#"
            i.material-icons menu
    #main-content class="#{increase_margin_container}"
      .container
        .row
          = notice_and_alert_messages if flash.any?
      == yield
    footer.page-footer.cyan.darken-1
      .container
        .row
          .col.l9.s12
            h5.white-text ¿Quienes somos?
            p.white-text.text-lighten-4 Somos una compañia joven interesada en mejorar la vida de aquellas personas que necesitan asistencia personal para llevar una vida mas comoda.
          .col.l3.s12
            ul
              li
                == link_to 'Terminos y condiciones', terms_and_conditions_path, class: 'white-text'
              li
                == link_to 'Aviso de privacidad', privacy_policy_path, class: 'white-text'
              li
                == link_to 'Preguntas frecuentes', faq_path, class: 'white-text'
              li
                == link_to 'Contacto', contact_path, class: 'white-text'
      .footer-copyright
        .container.center
          | Asisteme &copy; 2015